jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.2.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update
            sudo apt-get -y install curl jq git
            npm install
      - run:
          name: "Run test suites"
          command: npm test
  deploy:
    docker:
      - image: cimg/node:15.2.1
    environment:
        - APP_ID: plamjaipkjccppcicaomjnggmiencmhf
    steps:
      - checkout
      - run:
          name: "Package Extension"
          command: git archive -o extension.zip HEAD
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T extension.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"

version: 2.1
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
